### ISSUE TITLE
Bug - All Endpoints can't download

### ISSUE THREAD

**Issue by Zaigaochu** [yogeshojha/rengine#643] opened 2022-06-02 08:21 UTC
Scan History---All Endpoints can't download

**Comment by yogeshojha** [comment] 2022-06-05 17:18
Hi, can you please right click, inspect element, go to console and paste the error? I can download the URLs tho, so need to figure out, please attach console log.

**Comment by davidfegyver** [comment] 2022-06-05 18:08
Hey!
@yogeshojha,
You've put together a really awesome tool, congrats :) If only I was a good programmer and could help this project 🥺

here are some screenshots from the error

![image](https://user-images.githubusercontent.com/56135029/172063866-6029d407-929c-49c3-893c-c456fb61333f.png)
![image](https://user-images.githubusercontent.com/56135029/172063949-6117167c-0028-4842-8ea8-a2170d78bf55.png)


@Zaigaochu You can solve it for now, by pasting this into the console: 
```
download_subdomains(scan_id=null, domain_id=null, domain_name='') // to download subdomains
download_endpoints(scan_id=null, domain_id=null, domain_name='', pattern=null) // to download endpoints
```

**Comment by Zaigaochu** [comment] 2022-06-06 08:49
Thank you for your answer。
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/53184190/172127345-c4844193-6367-4b65-a7cb-62f665b76ea0.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/53184190/172127617-4560d7ba-4f22-440f-aafa-5e6d5e3c1834.png">
There "Download ALL Subdomain" and "Download ALL Endpoints" function does not take effect。

**Comment by yogeshojha** [comment] 2022-08-10 07:08
Hi @davidfegyver Thank you for pointing this out. I am surprised tho, how can domain name be empty :D Let me have a look

Thanks again

**Comment by davidfegyver** [comment] 2022-08-10 07:20
Hey @yogeshojha! It seems like the problem is not with the `domain_name`, but with `domain_id` which has an equal sign after it, causing syntax errors.

**Comment by yogeshojha** [comment] 2022-08-12 12:57
Thank you @davidfegyver I have now fixed this. :rocket:

**Closed** 2022-08-12 12:57 UTC
