### ISSUE TITLE
Instructions for adding public certificates to Docker web proxy nginex to avoid cert error on browsers using VPS

### ISSUE THREAD

**Issue by apskis** [yogeshojha/rengine#601] opened 2022-03-15 19:32 UTC
**Is your feature request related to a problem? Please describe.**
When setting up rengine on a VPS server, the browsers get a certificate error because the docker container for nginex is using self-signed certs. 

**Describe the solution you'd like**
Some options or instructions on how to update the containers to use my own purchased certificates

**Describe alternatives you've considered**
Googling all day long on how to do this myself realizing I can't seem to understand how docker works to set this up myself

**Additional context**
I don't mind do the work myself I just can't seem to figure out how without breaking everything. I am not well versed with docker. Any help on this would be appreciated.

**Comment by psyray** [comment] 2023-11-17 23:23
Duplicate of #506

**Closed by psyray** 2023-11-17 23:23 UTC
Labels: feature_request
