### ISSUE TITLE
Adding Nuclei Templates as zip

### ISSUE THREAD

**Issue by ratpunk2** [yogeshojha/rengine#508] opened 2021-09-29 07:13 UTC
Thanks for this awesome tool. I was wondering if it is possible for devs to introduce the feature to upload the nuclei templates as zip file because atm Rengine users are need to select and upload them one by one which is really time taking. 

By the way, the new UI looks dope af.

Thanks.

**Comment by yogeshojha** [comment] 2021-10-02 15:50
Zip will be an overkill, but we can let you choose multiple templates via upload box, how does that sound?

**Comment by ratpunk2** [comment] 2021-10-03 09:06
@yogeshojha Sound fantastic to me as users will be able to upload the temps in no time :) 

Thanks for considering and labeling it a top priority one.

**Comment by psyray** [comment] 2023-11-17 21:07
Duplicate of #461

**Closed by psyray** 2023-11-17 21:07 UTC
Labels: top-priority, feature_request, 2.0.0
