### ISSUE TITLE
Support for Let's Encrypt SSL CERTS

### ISSUE THREAD

**Issue by 0xtejas** [yogeshojha/rengine#512] opened 2021-10-02 11:41 UTC
**Is your feature request related to a problem? Please describe.**
Browsers don't like custom signed SSL certs.

**Describe the solution you'd like**
Let's Encrypt certs can help resolve this

**Comment by psyray** [comment] 2023-11-17 21:02
Duplicate of #506

**Closed by psyray** 2023-11-17 21:02 UTC
Labels: top-priority, feature_request
