### ISSUE TITLE
bug: Tools Arsenal Server Error (500)

### ISSUE THREAD

**Issue by bausastra** [yogeshojha/rengine#1064] opened 2023-11-22 03:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, thanks for this tool. Permission to ask, when I try to add a tool to the arsenal, when I click add. The output is **"server error (500)"** and when you open the arsenal tools tab a display like that will appear, where previously whatever tools were installed in the Tools Arsenal section. Please give me recommendations to fix it

Thank you

![Screenshot 2023-11-22 102030](https://github.com/yogeshojha/rengine/assets/142311887/8fbb3ddf-524e-44a5-b018-44c2499b0991)

### Expected Behavior

Can add External tools and view Tools Arsenal Tab

### Steps To Reproduce

1. Click Settings, choose Tools Arsenal 
2. See error "Server Error (500)

### Environment

```markdown
- reNgine: 2.0.0
- OS: Ubuntu 22.04.3 Jammy LTS 
- Python: Python 3.10.12
- Docker Engine: Docker version 24.0.6, build ed223bc
- Docker Compose: Docker Compose version v2.21.0
- Browser: Brave Version 1.60.118 Chromium: 119.0.6045.163 (Official Build)  (64-bit) & Firefox 119.0.1 (64-bit)
```

### Anything else?

Nothing

**Comment by AnonymousWP** [comment] 2023-11-22 14:38
Try updating to reNgine 2.0.1, as that fixes the issue: https://github.com/yogeshojha/rengine/releases/tag/v2.0.1. Let us know if that fixes the issue, so we can close this issue.

**Comment by psyray** [comment] 2023-12-04 23:02
@bausastra News ?

**Comment by psyray** [comment] 2023-12-09 14:18
@bausastra Can't reproduce issue on the latest release (2.0.2)
Update to the latest reNgine and check if problem persists.

**Closed by psyray** 2023-12-09 14:18 UTC
