### ISSUE TITLE
Feature - For multiple targets, add to organization

### ISSUE THREAD

**Issue by l3m0n** [yogeshojha/rengine#702] opened 2022-09-13 07:59 UTC
When 50 targets are added at one time, it is not convenient to add them to one organization. I think that when adding multiple targets, one can also be added to HTML, and these can be directly set as a certain organization

In addition, when adding a website to an organization, the operation of the drop-down box is also very inconvenient, because some sites are already classified as an organization, but it still appears. When there is a lot of data, it is not convenient to add multiple targets to an organization

**Comment by rootd4ddy** [comment] 2023-09-28 17:40
I think an easy resolution would be the ability to tag targets with the org during bulk import.

**Comment by psyray** [comment] 2023-11-17 23:52
Duplicate of #604

**Closed by psyray** 2023-11-17 23:52 UTC
Labels: feature_request

**Comment by SeanOverton** [comment] 2023-12-06 10:42
"In addition, when adding a website to an organization, the operation of the drop-down box is also very inconvenient, because some sites are already classified as an organization, but it still appears. When there is a lot of data, it is not convenient to add multiple targets to an organization" - This has been addressed in: https://github.com/yogeshojha/rengine/pull/1106

Addressing the bulk upload of targets to an organisation via the csv upload in this PR -> https://github.com/yogeshojha/rengine/pull/1109
