### ISSUE TITLE
bug: goofuzz not properly working

### ISSUE THREAD

**Issue by jaykumarjp** [yogeshojha/rengine#1177] opened 2024-01-24 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/usr/src/github/goofuzz/GooFuzz -t facebook.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt

/usr/src/github/goofuzz/GooFuzz -t twitter.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt

/usr/src/github/goofuzz/GooFuzz -t youtube.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt

### Expected Behavior

/usr/src/github/goofuzz/GooFuzz -t redacted.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt

/usr/src/github/goofuzz/GooFuzz -t redacted.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt

/usr/src/github/goofuzz/GooFuzz -t redacted.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt

### Steps To Reproduce

scan and check logs, 
in goofuzz -t for target but in rengine diffrent sites are in target

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by psyray** [comment] 2024-02-21 11:51
@jaykumarjp Thanks for your issue but it's really not understandable.
Add more context
Without your feedback next week we will close this issue
And fill seriously the environment vars

**Comment by Ovi3** [comment] 2024-02-23 03:05
I think this is not a bug.  `/usr/src/github/goofuzz/GooFuzz -t facebook.com -d 3 -p 2 -w redacted.in -o /usr/src/scan_results/redacted.in_16/gofuzz.txt` mean something like: using "site:facebook.com redacted.in" in google search to search info about redacted.in in facebook.com site

**Closed** 2024-07-13 05:43 UTC
Labels: bug, release/2.1.1
