### ISSUE TITLE
Port scanning failed - version 1.3.3

### ISSUE THREAD

**Issue by MikJagger** [yogeshojha/rengine#674] opened 2022-07-28 13:07 UTC
### Issue Summary

After a in-place upgrade from 1.2.0 to 1.3.0 with steps as documented below all new scan fail on the 'Port scanning' module with below error:

Port Scanning: Failed
Error: [Errno 2] No such file or directory: '/usr/src/scan_results/[TARGETURL]_898817779187/ports.json'

After the failed module the scan continues on the next module (OSINT) and eventually finishes the overall task with and failed status.

I did not do a new deployment yet for testing purposes but wanted to report the potential bug based on the in-place upgrade scenario up front. 

### Technical details
Deployment is based on a Ubuntu 20.04 VPS (Azure IaaS)
Rengine version in-place upgrade from 1.2.0 to 1.3.0
Upgrade method used https://rengine.wiki/update/ see detailed update instructions

**Comment by EasyNV** [comment] 2022-08-05 08:01
Hi, I also stumble upon the same issues.

My problem is because I set the `use_naabu_config` to `true`. It will add `-config` flag when running naabu, but it looks like naabu currently will automatically look for configuration file at `$HOME/.config/naabu/config.yaml`.

Ref: https://github.com/projectdiscovery/naabu#configuration-file

**Comment by MikJagger** [comment] 2022-08-16 08:28
(in-place) update from 1.3.0 to 1.3.1 solved the issue.

**Comment by MikJagger** [comment] 2022-11-06 19:40
Today I stumbled on the same issue when performing a new clean install on below setup. Reopened the ticket. Solution as suggested by EasyNV is not applicable for a (default) install (no custom engine configs). 

Issue Summary

Port Scanning: Failed
Error: [Errno 2] No such file or directory: '/usr/src/scan_results/[TARGETURL]_898817779187/ports.json'

After the failed module the scan continues on the next module (OSINT) and eventually finishes the overall task with and failed status.

Technical details:
Deployment is based on a Ubuntu 22.04.1 LTS (VPS (Azure IaaS)
Rengine version  1.2.0 to 1.3.3
First scan after default installs failed with error.

**Comment by ad0nis** [comment] 2022-11-11 21:39
Can confirm that this is an issue. I just completely reset old install, updated, re-built, setup a new target and reproduced this issue immediately.

**Comment by EasyNV** [comment] 2022-11-18 08:57
Hi, sorry just see notification on this issue thread.

You need to use a custom scan engine configuration in order for the fix to work as the default one always set the options for `use_naabu_config` to `true`.

**Comment by mazapepsi** [comment] 2022-11-30 11:22
is there any fix for this, i am on version 1.3.4 and issue persists. Tried both `use_naabu_config` to `true` and `false`. Infact i dont' even wan't to use naabu. I am trying to use `smap` in rengine. So i added `uses_tool: [smap]` under `port_scan` section. But this naabu error is messing it up. Can i do it some otherway

**Closed** 2023-03-22 04:19 UTC

**Comment by x0d3** [comment] 2023-07-19 11:02
rather its true or false its not working 
rengine-v: 1.3.6

**Comment by haimtoledano** [comment] 2023-09-05 14:15
same here rengine-v: 1.3.6
