### ISSUE TITLE
Multiple file upload option 

### ISSUE THREAD

**Issue by 0xtejas** [yogeshojha/rengine#517] opened 2021-10-08 15:21 UTC
**Is your feature request related to a problem? Please describe.**
Wasn't able to upload multiple config files for nuclei, I guess this is case for all upload part in the program

**Describe the solution you'd like**
Allow multiple upload of files

**Comment by psyray** [comment] 2023-11-17 21:08
Duplicate of #461

**Closed by psyray** 2023-11-17 21:08 UTC
Labels: top-priority, feature_request
