### ISSUE TITLE
v 2.0.1 Scan Findings - Directories - No data available in table, and dir scan never ends

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1018] opened 2023-10-25 09:11 UTC
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Dir scan to complete and data in db

### Anything else?

Full scan

Directories & files fuzz    In progress

Logs for scan #1
ffuf -w /usr/src/wordlist/dicc.txt -e html,php,git,yaml,conf,cnf,config,gz,env,log,db,mysql,bak,asp,aspx,txt,conf,sql,json,yml,pdf -p 0.05 -recursion -recursion-depth 2 -t 30 -timeout 5 -ac -mc 200,204 -u https://ginandjuice.shop/FUZZ -json
null

Scan Findings
Directories
No data available in table

**Comment by zinwelzl** [comment] 2023-10-25 09:30
Running ffuf in kali terminal ended in just 20 minutes, not in VPS that have more power where I run Rengine.
This is output.

ffuf -w dicc.txt -e html,php,git,yaml,conf,cnf,config,gz,env,log,db,mysql,bak,asp,aspx,txt,conf,sql,json,yml,pdf -p 0.05 -recursion -recursion-depth 2 -t 30 -timeout 5 -ac -mc 200,204 -u https://ginandjuice.shop/FUZZ -json 

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v2.1.0-dev
________________________________________________

 :: Method           : GET
 :: URL              : https://ginandjuice.shop/FUZZ
 :: Wordlist         : FUZZ: /home/kali/rengine-2.0_release/dicc.txt
 :: Extensions       : html php git yaml conf cnf config gz env log db mysql bak asp aspx txt conf sql json yml pdf 
 :: Follow redirects : false
 :: Calibration      : true
 :: Timeout          : 5
 :: Threads          : 30
 :: Delay            : 0.05 seconds
 :: Matcher          : Response status: 200,204
________________________________________________

{"input":{"FFUFHASH":"MTNmMWI0MzM1","FUZZ":"YWJvdXQ="},"position":17205,"status":200,"length":11166,"words":4749,"lines":167,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/about","duration":52536284,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWJhOGZm","FUZZ":"YmxvZw=="},"position":43263,"status":200,"length":10923,"words":4515,"lines":173,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/blog","duration":51192800,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWJiNjcz","FUZZ":"YmxvZw=="},"position":46707,"status":200,"length":10923,"words":4515,"lines":173,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/blog","duration":50630394,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWJiNjg5","FUZZ":"QmxvZw=="},"position":46729,"status":200,"length":10905,"words":4513,"lines":173,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/Blog","duration":54308897,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWJiZDY5","FUZZ":"Y2F0YWxvZw=="},"position":48489,"status":200,"length":16798,"words":7222,"lines":287,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/catalog","duration":54706421,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWIxMDI2Yg==","FUZZ":"ZmF2aWNvbi5pY28="},"position":66155,"status":200,"length":15406,"words":11,"lines":1,"content-type":"image/x-icon","redirectlocation":"","url":"https://ginandjuice.shop/favicon.ico","duration":53269947,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWIxNDFjMQ==","FUZZ":"bG9naW4="},"position":82369,"status":200,"length":7451,"words":3344,"lines":133,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/login","duration":55731829,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWIxNDFkNw==","FUZZ":"TG9naW4="},"position":82391,"status":200,"length":7442,"words":3343,"lines":133,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/Login","duration":56669798,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
{"input":{"FFUFHASH":"MTNmMWIxNDNlNw==","FUZZ":"bG9naW4v"},"position":82919,"status":200,"length":7451,"words":3344,"lines":133,"content-type":"text/html; charset=utf-8","redirectlocation":"","url":"https://ginandjuice.shop/login/","duration":52898434,"scraper":{},"resultfile":"","host":"ginandjuice.shop"}
:: Progress: [131164/131164] :: Job [1/1] :: 289 req/sec :: Duration: [0:13:47] :: Errors: 9079 ::

**Comment by zinwelzl** [comment] 2023-10-25 09:50
Running same in
docker exec -it rengine_celery_1 bash
get same result, but no data in database.

**Comment by psyray** [comment] 2023-10-25 13:15
FFUF did not finish also for me, but it records data to the db
I've tested with a small wordlist without extensions to be sure to have results and test the db save
Here's is the scanEngine conf
```
dir_file_fuzz: {
  'auto_calibration': true,
  'enable_http_crawl': true,
  'rate_limit': 150,
  'extensions': [],
  'follow_redirect': false,
  'max_time': 0,
  'match_http_status': [200,204,301,302,307,401,403,405,500],
  'recursive_level': 2,
  'stop_on_error': false,
  'timeout': 5,
  'threads': 100,
  'wordlist_name': 'fuzz_boom'
}
```

FFUF stop scanning for an unknown reason at ~ 1/4 of the progress (here is the logs from the **Scan Timeline** on the scan history Dashboard that stopped at **admin/user_count** ~ 1000/4842)
![image](https://github.com/yogeshojha/rengine/assets/1230954/56ea8f59-959d-4498-bcb3-bb275a55d29a)

Task never finish, I need to stop it into subscan history to remove ffuf process

I've took the command line from the logs popup and launched in celery container
`ffuf -w /usr/src/wordlist/fuzz_boom.txt -p 0.015 -recursion -recursion-depth 2  -t 100 -timeout 5 -ac -mc 200,204,301,302,307,401,403,405,500 -u https://ginandjuice.shop/FUZZ -json`

Scan finish in 3sec
![image](https://github.com/yogeshojha/rengine/assets/1230954/13998049-3678-4899-83b0-eb4eaa182e31)

So db save is working, but FFUF never finish

**Comment by psyray** [comment] 2023-10-25 13:17
> Running same in docker exec -it rengine_celery_1 bash get same result, but no data in database.

Results are saved to DB from terminal output, so it's normal that there's no save when launched from terminal

**Comment by psyray** [comment] 2023-10-25 13:21
Duplicate of #1006

**Closed** 2023-10-26 09:39 UTC
Labels: feature_request
