### ISSUE TITLE
Fed  Dirsearch/ffuf  with Right Directory Bruteforcing File - Making Rengine Intelligent

### ISSUE THREAD

**Issue by attacker007** [yogeshojha/rengine#184] opened 2020-07-30 14:45 UTC
Hi @yogeshojha 

Common mistake which I've noticed in almost all Recon tools is that they are feeding dirsearch/ffuf with the same directory bruteforce file to each type of subdomain. Currently rengine is using dirsearch which uses its default dict file for bruteforcing.

If httpx or wappalyzer is giving information that subdomain is wordpress. Then that wordpress subdomain should be tested against this directory bruteforcing list

```
https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/CMS/wordpress.fuzz.txt

```

Similarly one can do it for each type of systems like SAP etc. (Should be done for as much type of system Dirs we have in SecLists by danielmiessler )

Regards,

**Comment by yogeshojha** [comment] 2020-11-30 10:15
Yay ffuf is coming. Duplicate of #146

**Closed** 2020-11-30 10:15 UTC
Labels: feature_request
