### ISSUE TITLE
Is there any option where we can upload multiple nuclei template at once

### ISSUE THREAD

**Issue by thedr34mb0y** [yogeshojha/rengine#835] opened 2023-03-08 12:03 UTC
**Is your feature request related to a problem? Please describe.**
RenGine supports uploading custom nuclei templates however we can upload these templates one by one, which is time-consuming for sure.

**Describe the solution you'd like**
Please make a bulk yaml upload button or just give a path where this template exists so we can manually copy all templates to that path. 

Thanks!

**Comment by UncleJ4ck** [comment] 2023-08-10 10:23
@yogeshojha i don't know if we can re-open this issue because, it's highly recommended and it will optimize us a lot of time by bulk upload the nuclei-templates

**Comment by psyray** [comment] 2023-11-18 17:04
Duplicate of #461 
Look workaround here
https://github.com/yogeshojha/rengine/issues/461#issuecomment-1670121467

**Closed by psyray** 2023-11-18 17:04 UTC
Labels: feature_request
